DELETE FROM gallery_photos;

INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Personal/img11.jpg', 'Personal Photo 1', null, 'Personal');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Personal/img157.jpg', 'Personal Photo 2', null, 'Personal');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Personal/img52.jpg', 'Personal Photo 3', null, 'Personal');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Personal/img60.jpg', 'Personal Photo 4', null, 'Personal');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Personal/img68.jpg', 'Personal Photo 5', null, 'Personal');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Personal/PHOTO-2026-07-25-14-24-22 2.jpeg', 'Personal Photo 6', null, 'Personal');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/Gemini_Generated_Image_3q2scv3q2scv3q2s.jpg', 'Family Photo 1', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/Gemini_Generated_Image_jusckdjusckdjusc.jpg', 'Family Photo 2', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/Gemini_Generated_Image_nvk2o8nvk2o8nvk2.jpg', 'Family Photo 3', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/grandpa old photo.jpg', 'Family Photo 4', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/graps 2 .jpg', 'Family Photo 5', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/image .jpg', 'Family Photo 6', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img101.jpg', 'Family Photo 7', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img11 (2).jpg', 'Family Photo 8', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img116.jpg', 'Family Photo 9', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img124.jpg', 'Family Photo 10', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img128.jpg', 'Family Photo 11', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img132.jpg', 'Family Photo 12', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img136.jpg', 'Family Photo 13', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img141.jpg', 'Family Photo 14', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img145.jpg', 'Family Photo 15', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img149.jpg', 'Family Photo 16', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img15.jpg', 'Family Photo 17', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img153.jpg', 'Family Photo 18', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img165.jpg', 'Family Photo 19', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img169.jpg', 'Family Photo 20', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img19.jpg', 'Family Photo 21', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img27.jpg', 'Family Photo 22', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img31.jpg', 'Family Photo 23', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img35.jpg', 'Family Photo 24', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img40.jpg', 'Family Photo 25', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img44.jpg', 'Family Photo 26', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img5 (2).jpg', 'Family Photo 27', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img56.jpg', 'Family Photo 28', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img64.jpg', 'Family Photo 29', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img73.jpg', 'Family Photo 30', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img77.jpg', 'Family Photo 31', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img85.jpg', 'Family Photo 32', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img93.jpg', 'Family Photo 33', null, 'Family');
INSERT INTO gallery_photos (url, title, caption, album) VALUES ('/gallery/Family/img97.jpg', 'Family Photo 34', null, 'Family');

