DELETE FROM gallery_photos;

INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Personal/img11.jpg', null, 'Personal', 1);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Personal/img157.jpg', null, 'Personal', 2);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Personal/img52.jpg', null, 'Personal', 3);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Personal/img60.jpg', null, 'Personal', 4);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Personal/img68.jpg', null, 'Personal', 5);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Personal/PHOTO-2026-07-25-14-24-22 2.jpeg', null, 'Personal', 6);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/Gemini_Generated_Image_3q2scv3q2scv3q2s.jpg', null, 'Family', 7);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/Gemini_Generated_Image_jusckdjusckdjusc.jpg', null, 'Family', 8);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/Gemini_Generated_Image_nvk2o8nvk2o8nvk2.jpg', null, 'Family', 9);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/grandpa old photo.jpg', null, 'Family', 10);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/graps 2 .jpg', null, 'Family', 11);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/image .jpg', null, 'Family', 12);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img101.jpg', null, 'Family', 13);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img11 (2).jpg', null, 'Family', 14);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img116.jpg', null, 'Family', 15);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img124.jpg', null, 'Family', 16);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img128.jpg', null, 'Family', 17);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img132.jpg', null, 'Family', 18);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img136.jpg', null, 'Family', 19);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img141.jpg', null, 'Family', 20);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img145.jpg', null, 'Family', 21);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img149.jpg', null, 'Family', 22);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img15.jpg', null, 'Family', 23);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img153.jpg', null, 'Family', 24);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img165.jpg', null, 'Family', 25);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img169.jpg', null, 'Family', 26);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img19.jpg', null, 'Family', 27);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img27.jpg', null, 'Family', 28);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img31.jpg', null, 'Family', 29);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img35.jpg', null, 'Family', 30);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img40.jpg', null, 'Family', 31);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img44.jpg', null, 'Family', 32);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img5 (2).jpg', null, 'Family', 33);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img56.jpg', null, 'Family', 34);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img64.jpg', null, 'Family', 35);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img73.jpg', null, 'Family', 36);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img77.jpg', null, 'Family', 37);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img85.jpg', null, 'Family', 38);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img93.jpg', null, 'Family', 39);
INSERT INTO gallery_photos (image_url, caption, album_name, sort_order) VALUES ('/gallery/Family/img97.jpg', null, 'Family', 40);

